### ISSUE TITLE
Ghost dynamic image URLs are serving wrong images

### ISSUE THREAD

**Issue by 1DxSU1t6** [TryGhost/Ghost#10912]
### Issue Summary

In certain situation (see below), Ghost dynamic image URLs will serve wrong image.

### To Reproduce

1. Upload an image named test_o.jpg (say, a cat)
2. Upload an image named test.jpg (say, a dog)
3. View your uploaded image (say, http://localhost:2368/content/images/2019/07/test.jpg) – it shows a dog
4. View a sized version of the same image (say, http://localhost:2368/content/images/size/w2000/2019/07/test.jpg) – you see a cat!

Unfortunately this example is not too contrived; e.g., the idea to add _o to designate the original photo before editing it is not uncommon. It's also easy to fix.

### Technical details:

The problem is lines 58-65 here: https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/server/web/shared/middlewares/image/handle-image-sizes.js#L58 . It assumes that the optimized image has the same `imageNumber` as the original, which of course is not always the same – as my example shows.

Suggested fix: please simply save the original images in a different folder – in that case, the original and optimized image will have exactly the same filename, so getting one from the other will be simple and deterministic. For consistency with `.../size/wXXX/...` URLs, could I suggest to save the original image as `.../size/original/...`?

**Comment by allouis** [comment]
Hey @1DxSU1t6 nice catch :fishing_pole_and_fish: 

Luckily this is the first report so hopefully it isn't too widespread of an issue!

I think your suggested fix would work, however it has some problems, mainly that it would affect people's existing installations if they upgraded - we would either need the code to check two places for the original OR would need some kind of migration at the StorageAdapter level. 

One way to get around this would be to remove any trailing `"_o"` from the filename (with extension remove) upon upload - this would get rid of the issue without requiring extra work for existing installations

**Comment by 1DxSU1t6** [comment]
Hi @allouis , thanks for taking a look, and I wouldn't mind helping with this (not fast though, as I'm traveling and really busy). I took a quick look and it seems the `"_o"` suffix has more issues that won't be solved by just removing any trailing `"_o"` from the file names:

1. say, a user has image optimization disabled, and uploads `test.jpg`. Then later the user enables image optimization and uploads another `test.jpg`. The optimizer will save it as `test-1.jpg`, but the optimized version as `test_o.jpg` because that name is available. Now we got wrong images again.

2. say, a user uploads `test-1.jpg`, and an optimizer saves `test-1_o.jpg`. However, the code in https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/server/web/shared/middlewares/image/handle-image-sizes.js#L58 would parse `-1` as a number and look for the original in `test_o-1.jpg` – so the responsive images won't work for such filenames at all.

So I see two options:

1. Add a special API to `LocalFileStorage.js` to save a pair of optimized/original images. That API would pick a unique name such that both optimized and original file names are available (i.e., will increase `n` until both `test_${n}.jpg` AND `test_o-${n}.jpg` are available. The regular save function will do the same – except it won't save the original image, ensuring that the file for the original image doesn't exist. That keeps the existing naming convention, but is quite messy.

2. Also add a special API to `LocalFileStorage.js`, but use `/size/original/` naming convention, plus a migration code (or indeed just look up in two places). Keep code cleaner, but need a migration.

Any thoughts on which approach is better?

Re. custom storage adapters, unfortunately I can't find a reasonable way to fix them without changing them. The problem is that you need coordination before two save() calls (for the original and optimized images) – and the current API doesn't allow that.

**Comment by ErisDS** [comment]
@1DxSU1t6 At first glance, it seems like storing the original file on a different path, rather than with a different name, would probably have been the better approach.

The `/size/` directory is considered "throwaway"... e.g. imagine if you changed all sizes in your theme, you could delete the `/size/` directory to get rid of all the images there that won't be used any more, and they'd get regenerated on future requests. So storing originals inside the `/size/` directory isn't the right approach - maybe just `/content/images/original/` instead.

**Comment by 1DxSU1t6** [comment]
Yes, I think that's the most reasonable solution. Otherwise, you'd need to remove trailing `_o`, also `-1` and even `-01-01-2019` (as today's algorithm will look for `_o-2019` as the original image for this).

What I'd appreciate advice on is how to handle migration. Would just writing a migration that renames all _o images be fine? Should it rename or just copy to keep it safer (but slower)?

**Comment by 1DxSU1t6** [comment]
Hi @ErisDS, @allouis, I put some work into fixing this issue following the idea outlined by @ErisDS. Everything is completed except migrations and tests – but I outlined my idea for the migration in the code comments.

Could you please take a look and let me know if this is the right direction? If so, I'll finish the migration and will add tests.

**Comment by sampumon** [comment]
Oh no hello I hope this is still happening, the pull request is practically done!

I wonder if migration is even needed here? Original and optimized images are already stored separate from `/size/` directory, and optimized have the original (without `_o`) filename. Are originals ever needed after upload, or would optimized be enough?

**Comment by tortxoFFoxtrot** [comment]
Does the _o version of the image retain exif metadata?
