### ISSUE TITLE
Uncaught SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by goodbytes-gb** [TryGhost/Ghost#8815]
### Issue Summary

After a clean install of Ghost, I am unable to access `/ghost` to setup a user account for my blog. I get a continuous loading spinner, nothing else happens. Upon inspection of console I can see two errors:

`Uncaught SyntaxError: Unexpected string` in `vendor.min-md5` and `ghost.min-md5`

<img width="1458" alt="screen shot 2017-08-01 at 23 29 19" src="https://user-images.githubusercontent.com/850149/28849921-5f853d4e-7711-11e7-9f68-b071176e5a3d.png">

Some users are complaining about this in Slack chat, and it's also similar to issue #8782 

### Steps to Reproduce

1. Install ghost
2. Navigate to /ghost

### Technical details:

* Server: Ubuntu
* Ghost Version: 1.3.0 (cli 1.0.3)
* Node Version: 6.11.2
* Browser/OS: macOS Sierra, Chrome and Safari
* Database: MySQL

**Comment by ErisDS** [comment]
@goodbytes-gb you're correct that multiple people are seeing this - could you share how you solved it?

**Comment by goodbytes-gb** [comment]
@ErisDS The blog is under CloudFlare, I disabled the cache by enabling development mode and it started working again. A quick Google took me to this page: https://docs.ghost.org/v1.0.0/docs/troubleshooting - which suggests adding a page rule to disable caching of admin assets (slightly different issue, but makes sense!).

I've added a rule `/ghost*` to bypass the cache.

Everything seemed to work from here on out... Assuming this wasn't an issue with Ghost I decided to close the issue. However, I just tried to access it again and it I got the same issue with the page rule in place.

I tested again by enabling development mode in CF, again, this fixed the issue.

I'm back to square one so I'll reopen this.

**Comment by ErisDS** [comment]
I believe the correct solution is to disable caching, rocket loader and autominify for /ghost*. If you can test and confirm I will update the troubleshooting guide.

**Comment by goodbytes-gb** [comment]
@ErisDS Thanks for the update, you are correct.

Previously I used only 'Bypass Cache'... I have also added 'Disable Performance'.

![screen shot 2017-08-02 at 13 47 31](https://user-images.githubusercontent.com/850149/28874336-58717982-7789-11e7-8df8-c072c3128f79.png)

The issue is now fixed. Thank you :)

**Comment by ErisDS** [comment]
Cool, so I've also updated the documentation to reflect this, and as its such a common problem added callouts to both the upgrade and install guide. Hopefully this will help!

**Comment by whitfin** [comment]
@ErisDS @goodbytes-gb can confirm that this fixes the issue in browser, but it appears to still have issues from Ghost Desktop - any ideas why that would be?

**Comment by goodbytes-gb** [comment]
@whitfin I've never used it sorry. I would have thought it was just a wrapper for the web and would therefore work.

**Comment by whitfin** [comment]
@goodbytes-gb that's what I thought, but appears not to be. Issue persists but is fine on web.
