### ISSUE TITLE
logging transports doesn't convert configuration input to an array

### ISSUE THREAD

**Issue by esatterwhite** [TryGhost/Ghost#8940]
### Issue Summary
https://github.com/TryGhost/Ghost/blob/master/core/server/config/env/config.production.json#L22
If I specify a single logging transport, this throws an error, 
```
        this.transports.forEach((transport) => {
                        ^

TypeError: this.transports.forEach is not a function
    at new GhostLogger (/home/esatterwhite/dev/js/ghost-blog/versions/1.7.1/node_modules/ghost-ignition/lib/logging/GhostLogger.js:54:25)
    at createNewInstance (/home/esatterwhite/dev/js/ghost-blog/versions/1.7.1/node_modules/ghost-ignition/lib/logging/index.js:10:19)
    at Object.<anonymous> (/home/esatterwhite/dev/js/ghost-blog/versions/1.7.1/core/server/logging.js:4:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/esatterwhite/dev/js/ghost-blog/versions/1.7.1/core/server/index.js:20:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

1. 
```
node current/index.js --logging:level=error --logging:transports=file
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.7
* Node Version: 6.11
* Browser/OS:  N/A
* Database: N/A

**Comment by esatterwhite** [comment]
this would also be the case if you were using ENV vars

```
logging__transports=file
```

**Comment by vikaspotluri123** [comment]
According to the docs, this is a known issue ([link](https://docs.ghost.org/docs/config))

 `Arrays as in logging__transports=[...] are currently not supported. This is a known issue.
Env vars should be lowercase, we realise this is a little odd, it's a limitation of nconf, but they do work!`

**Comment by esatterwhite** [comment]
It errors with command line arguments as well. the env var is not the issue, the issue is the code is assumes an array, but nconf will does not guarantee that the value is one.

**Comment by esatterwhite** [comment]
```js
const _transports = nconf.get('transports')
const transports = Array.isArray(_transports) ? _transports : [_transports]
```

or even `transports.split(',')`
that would allow for env vars

```
logging__transports=file,stdout
```

**Comment by kirrg001** [comment]
Hey @esatterwhite 👋 

Passing a single value as logging transport is right now unsupported. Could you please raise an issue [here](https://github.com/TryGhost/Ignition) instead? A PR is welcome to support single values 👍 

And passing the transports as array via argv, does not work as mentioned in the [docs](https://docs.ghost.org/docs/config), because of a bug in nconf. I've already pushed a PR to nconf to sort this out.

Closing as this is not a bug in Ghost.

**Comment by esatterwhite** [comment]
@kirrg001, you can do array arguments w/ argv, you just specify the flag more than once. 
```
--logging:transports=file --logging:transports=stdout
```

this works, nconf converts it to an array

```javscript
{
  "logging": {
    "transports": ["file", "stdout"]
  }
}
```

**Comment by esatterwhite** [comment]
```javascript
'use strict'
const config = require('./current/core/server/config')
console.log(config.get('logging:transports'))
```

```bash
$ node test.save --logging:transports=foo --logging:transports=bar --logging:transports=baz
$ [ 'foo', 'bar', 'baz' ]
```

**Comment by esatterwhite** [comment]
`yargs` does I should say

**Comment by BretFisher** [comment]
Just hit this issue a year later with ENV for `logging__transports=stdout` in Docker. Is there any update on array compatibility? How can we help, is the issue still with nconf?

**Comment by kirrg001** [comment]
@BretFisher [nconf](https://github.com/indexzero/nconf/pull/272) has merged the support for array parsing.

```
    nconf.env({
        separator: '__',
        parseValues: true
    });
```

We have to add a flag to tell `nconf` to parse arrays/objects using `parseValues`.

I'll re-open this issue now. PR is welcome 👍

**Comment by dnguneratne** [comment]
@kirrg001 In `\current\core\server\config\index.js` I tried changing:

```js
    nconf.env({
        separator: '__',
        parseValues: true
    });
```
But I get the same error:
```
Unhandled rejection TypeError: this.transports.forEach is not a function
    at new GhostLogger (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\ghost-ignition\lib\logging\GhostLogger.js:53:25)
    at createNewInstance (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\ghost-ignition\lib\logging\index.js:10:19)
    at Object.<anonymous> (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\core\server\lib\common\logging.js:4:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.get logging [as logging] (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\core\server\lib\common\index.js:15:16)
    at C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\index.js:31:12
    at tryCatcher (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\dna_g\MyStuff\projects\local_ghost\versions\2.2.0\node_modules\bluebird\js\release\promise.js:614:10)
```

**Comment by kirrg001** [comment]
@dnguneratne Did you update nconf locally?

**Comment by dnguneratne** [comment]
@kirrg001 Yes, this is on a local install.

**Comment by kirrg001** [comment]
> logging__transports='["stdout"]' node index.js
